services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - amazin-object-storage-node-1
      - amazin-object-storage-node-2
      - amazin-object-storage-node-3
    networks:
      - amazin-object-storage

  amazin-object-storage-node-1:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=ring
      - MINIO_SECRET_KEY=treepotato
    networks:
      - amazin-object-storage

  amazin-object-storage-node-2:
    image: minio/minio
    command: server --console-address ":9002" /data
    ports:
      - "9002:9002"
    environment:
      - MINIO_ACCESS_KEY=maglev
      - MINIO_SECRET_KEY=baconpapaya
    networks:
      - amazin-object-storage

  amazin-object-storage-node-3:
    image: minio/minio
    command: server --console-address ":9003" /data
    ports:
      - "9003:9003"
    environment:
      - MINIO_ACCESS_KEY=rendezvous
      - MINIO_SECRET_KEY=bluegreen
    networks:
      - amazin-object-storage

networks:
  amazin-object-storage:
    driver: bridge
    